server:
  port: 10000

spring:
  application:
    name: gateway-server # 服务名
  cloud:
    gateway:
      routes: # 路由配置
        - id: order-service # 路由 ID（唯一）
#          uri: http://localhost:8081 # 目标服务地址（可替换为 lb://service-name 实现负载均衡）
          uri: lb://service-order
          predicates: # 路由断言（匹配请求条件）
            - Path=/order/** # 匹配以 /api/ 开头的路径
          filters: # 路由过滤器（请求/响应处理）
            - StripPrefix=1 # 去除路径前缀（如 /api/user → /user）
            - AddRequestHeader=X-From-Gateway, true # 添加请求头
